/**
 * The three.js fighter: the skeleton spec, built and skinned.
 *
 * Everything about *what* the fighter does lives in `rig.ts`, `poses.ts` and `clips.ts`; this
 * file only knows how to build a body and push a resolved pose into it. That split is what
 * lets the choreography be unit-tested with no browser and no GPU, and it is why replacing
 * rigid primitives with a skinned mesh changed nothing above this line.
 *
 * The body is a `SkinnedMesh` over the rig's own 19 bones, with geometry generated by
 * `body.ts`. The previous version was a hierarchy of separate capsules and boxes, which is
 * why it read as made of sausages: rigid pieces cannot deform, so every joint was a visible
 * intersection of two solids. Skinning means the surface bends.
 *
 * Swapping in a rigged glTF character later still means replacing only this file: what it
 * consumes is joint rotations, which any humanoid rig accepts.
 */

import * as THREE from 'three';
import type { Joint, Vec3 } from './rig.ts';
import { JOINT_ORDER, SKELETON } from './rig.ts';
import type { ResolvedPose } from './blend.ts';
import type { MeshData } from './body.ts';
import { buildGloves, buildShorts, buildSkin } from './body.ts';
import { surfaceNoise } from './textures.ts';

export interface FighterPalette {
  readonly skin: number;
  readonly trunks: number;
  readonly gloves: number;
}

export const PALETTE_A: FighterPalette = { skin: 0xb07a52, trunks: 0xb8323d, gloves: 0xc4323a };
export const PALETTE_B: FighterPalette = { skin: 0x7d4d30, trunks: 0x2a5fc4, gloves: 0x2f5ed0 };

function toGeometry(data: MeshData): THREE.BufferGeometry {
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(data.positions, 3));
  geometry.setAttribute('uv', new THREE.Float32BufferAttribute(data.uvs, 2));
  geometry.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(data.skinIndices, 4));
  geometry.setAttribute('skinWeight', new THREE.Float32BufferAttribute(data.skinWeights, 4));
  geometry.setIndex(data.indices);
  geometry.computeVertexNormals();
  return geometry;
}

export class FighterModel {
  readonly root: THREE.Group;
  private readonly bones = new Map<Joint, THREE.Bone>();
  private readonly materials: THREE.Material[] = [];
  private readonly geometries: THREE.BufferGeometry[] = [];
  private readonly meshes: THREE.SkinnedMesh[] = [];

  constructor(palette: FighterPalette) {
    this.root = new THREE.Group();

    for (const joint of JOINT_ORDER) {
      const spec = SKELETON[joint];
      const bone = new THREE.Bone();
      bone.position.set(spec.offset[0], spec.offset[1], spec.offset[2]);
      const parent = spec.parent === null ? this.root : this.bones.get(spec.parent);
      if (!parent) throw new Error(`joint ${joint} has an unbuilt parent`);
      parent.add(bone);
      this.bones.set(joint, bone);
    }

    // Inverse bind matrices are taken from the bones as they stand, so the skeleton has to be
    // in its rest pose — and its world matrices up to date — at the moment it is constructed.
    this.root.updateMatrixWorld(true);
    const ordered = JOINT_ORDER.map((joint) => this.bones.get(joint)!);
    const skeleton = new THREE.Skeleton(ordered);

    const noise = surfaceNoise();

    // Skin: a dielectric with a faint sheen. The clearcoat stands in for sweat under the
    // lights, which is most of what separates a person from a mannequin on camera.
    const skin = new THREE.MeshPhysicalMaterial({
      color: palette.skin,
      roughness: 0.62,
      metalness: 0,
      clearcoat: 0.22,
      clearcoatRoughness: 0.45,
      sheen: 0.35,
      sheenColor: new THREE.Color(0xffd9c2),
      sheenRoughness: 0.7,
      roughnessMap: noise,
      bumpMap: noise,
      bumpScale: 0.0025,
    });
    const trunks = new THREE.MeshStandardMaterial({
      color: palette.trunks,
      roughness: 0.9,
      metalness: 0,
      roughnessMap: noise,
    });
    const gloves = new THREE.MeshPhysicalMaterial({
      color: palette.gloves,
      roughness: 0.42,
      metalness: 0,
      clearcoat: 0.55,
      clearcoatRoughness: 0.35,
      roughnessMap: noise,
    });
    this.materials.push(skin, trunks, gloves);

    for (const [data, material] of [
      [buildSkin(), skin],
      [buildShorts(), trunks],
      [buildGloves(), gloves],
    ] as const) {
      const geometry = toGeometry(data);
      this.geometries.push(geometry);
      const mesh = new THREE.SkinnedMesh(geometry, material);
      mesh.castShadow = true;
      mesh.receiveShadow = true;
      // Skinned bounds go stale as the pose changes; culling on them drops limbs mid-punch.
      mesh.frustumCulled = false;
      this.root.add(mesh);
      mesh.bind(skeleton);
      this.meshes.push(mesh);
    }
  }

  /** Pushes a resolved pose into the skeleton. Called once per fighter per frame. */
  applyPose(pose: ResolvedPose): void {
    for (const [joint, bone] of this.bones) {
      const rotation = pose.joints[joint];
      bone.rotation.set(rotation[0], rotation[1], rotation[2]);
    }
    const hips = this.bones.get('hips');
    if (hips) {
      const base = SKELETON.hips.offset;
      hips.position.set(base[0] + pose.offset[0], base[1] + pose.offset[1], base[2] + pose.offset[2]);
    }
  }

  setPlacement(position: Vec3, yaw: number): void {
    this.root.position.set(position[0], position[1], position[2]);
    this.root.rotation.y = yaw;
  }

  /** World position of the head, which the camera frames on. */
  headPosition(target: THREE.Vector3): THREE.Vector3 {
    const head = this.bones.get('head');
    if (!head) return target.set(0, 1.6, 0);
    return head.getWorldPosition(target);
  }

  dispose(): void {
    for (const geometry of this.geometries) geometry.dispose();
    for (const material of this.materials) material.dispose();
    for (const mesh of this.meshes) mesh.skeleton.dispose();
    this.geometries.length = 0;
    this.materials.length = 0;
    this.meshes.length = 0;
    this.bones.clear();
  }
}
