/**
 * The three.js fighter: the skeleton spec, built and skinned.
 *
 * Everything about *what* the fighter does lives in `rig.ts`, `poses.ts` and `clips.ts`; this
 * file only knows how to build a body and push a resolved pose into it. That split is what
 * lets the choreography be unit-tested with no browser and no GPU, and it is why replacing
 * rigid primitives with a skinned mesh changed nothing above this line.
 *
 * The body is a `SkinnedMesh` over the rig's own 19 bones, with geometry generated by
 * `body.ts`. The previous version was a hierarchy of separate capsules and boxes, which is
 * why it read as made of sausages: rigid pieces cannot deform, so every joint was a visible
 * intersection of two solids. Skinning means the surface bends.
 *
 * Swapping in a rigged glTF character later still means replacing only this file: what it
 * consumes is joint rotations, which any humanoid rig accepts.
 */

import * as THREE from 'three';
import type { Joint, Vec3 } from './rig.ts';
import { JOINT_ORDER, SKELETON } from './rig.ts';
import type { ResolvedPose } from './blend.ts';
import type { MeshData } from './body.ts';
import {
  buildBeard,
  buildFace,
  buildGloves,
  buildHair,
  buildShorts,
  buildSkin,
  occluders,
  occlusionAt,
  toneAt,
} from './body.ts';
import { surfaceNoise } from './textures.ts';
import type { FighterPalette } from './palette.ts';
import { PALETTE_A, PALETTE_B } from './palette.ts';

/**
 * Approximated subsurface scattering.
 *
 * Real skin is translucent: light enters, bounces around inside, and leaves reddened —
 * strongest where the flesh is thin and where the light is behind the subject. Without it a
 * lit body reads as painted stone, which is the single largest remaining tell after tone
 * mapping. three.js has no built-in scattering, so this injects the standard cheap
 * approximation: a forward-scatter term that peaks when the key light is behind the fighter,
 * modulated by a grazing-angle proxy for thinness, plus a gentle wrap so the terminator is a
 * gradient rather than a line.
 *
 * It is an approximation, not a solution — it does not know actual geometric thickness. At
 * broadcast distance it carries most of the read; in close-up it would not.
 */
const SUBSURFACE_MARKER = '#include <opaque_fragment>';

const SUBSURFACE_GLSL = `
  {
    vec3 ssViewDir = normalize( vViewPosition );
    vec3 ssLightDir = normalize( ( viewMatrix * vec4( uKeyDirection, 0.0 ) ).xyz );
    float ssBack = pow( clamp( dot( ssViewDir, -ssLightDir ), 0.0, 1.0 ), 3.0 );
    float ssThin = pow( 1.0 - clamp( dot( normal, ssViewDir ), 0.0, 1.0 ), 2.0 );
    float ssWrap = clamp( ( dot( normal, ssLightDir ) + 0.35 ) / 1.35, 0.0, 1.0 );
    outgoingLight += uSubsurface * uSubsurfaceStrength * ( ssBack * ssThin + 0.18 * ssWrap * ssThin );
  }
  ${SUBSURFACE_MARKER}`;

/** Direction the key light travels from, matching `scene.ts`. Kept in one place on purpose. */
const KEY_DIRECTION = new THREE.Vector3(2.6, 10.5, 3.4).normalize();

function skinMaterial(palette: FighterPalette, noise: THREE.Texture): THREE.MeshPhysicalMaterial {
  const material = new THREE.MeshPhysicalMaterial({
    color: palette.skin,
    roughness: 0.74,
    metalness: 0,
    // Occlusion and skin tone are baked into the mesh — see `shade`.
    vertexColors: true,
    // Clearcoat stands in for sweat under the lights, which is much of what separates a
    // person on camera from a mannequin.
    clearcoat: 0.1,
    clearcoatRoughness: 0.62,
    clearcoatRoughnessMap: noise,
    sheen: 0.22,
    sheenColor: new THREE.Color(0xffd9c2),
    sheenRoughness: 0.8,
    roughnessMap: noise,
    bumpMap: noise,
    bumpScale: 0.0032,
  });

  material.onBeforeCompile = (shader) => {
    shader.uniforms.uSubsurface = { value: new THREE.Color(palette.subsurface) };
    shader.uniforms.uSubsurfaceStrength = { value: 0.62 };
    shader.uniforms.uKeyDirection = { value: KEY_DIRECTION };
    shader.fragmentShader = shader.fragmentShader.replace(
      '#include <common>',
      `#include <common>
      uniform vec3 uSubsurface;
      uniform float uSubsurfaceStrength;
      uniform vec3 uKeyDirection;`,
    );
    if (!shader.fragmentShader.includes(SUBSURFACE_MARKER)) {
      // A silently failed string replace would cost the skin its scattering and look like a
      // tuning problem for hours. `animation.test.ts` guards the marker; this guards the run.
      throw new Error(`skin shader: three.js no longer emits ${SUBSURFACE_MARKER}`);
    }
    shader.fragmentShader = shader.fragmentShader.replace(SUBSURFACE_MARKER, SUBSURFACE_GLSL);
  };

  return material;
}

/** Exported so a test can assert three still emits the chunk the skin shader patches. */
export const SKIN_SHADER_MARKER = SUBSURFACE_MARKER;

function toGeometry(data: MeshData): THREE.BufferGeometry {
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(data.positions, 3));
  geometry.setAttribute('uv', new THREE.Float32BufferAttribute(data.uvs, 2));
  geometry.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(data.skinIndices, 4));
  geometry.setAttribute('skinWeight', new THREE.Float32BufferAttribute(data.skinWeights, 4));
  geometry.setIndex(data.indices);
  geometry.computeVertexNormals();
  return geometry;
}

/**
 * Bakes occlusion and skin tone into a vertex colour attribute.
 *
 * Done here rather than in `body.ts` because it needs the normals, and the normals are three's
 * to compute. It runs once per fighter at construction — a few thousand vertices against a few
 * dozen occluders — and costs nothing per frame thereafter.
 */
function shade(geometry: THREE.BufferGeometry, tone: boolean): void {
  const position = geometry.getAttribute('position');
  const normal = geometry.getAttribute('normal');
  const balls = occluders();
  const colors = new Float32Array(position.count * 3);
  for (let i = 0; i < position.count; i++) {
    const point: [number, number, number] = [position.getX(i), position.getY(i), position.getZ(i)];
    const facing: [number, number, number] = [normal.getX(i), normal.getY(i), normal.getZ(i)];
    const ao = occlusionAt(point, facing, balls);
    const [r, g, b] = tone ? toneAt(point) : [1, 1, 1];
    colors[i * 3] = ao * r;
    colors[i * 3 + 1] = ao * g;
    colors[i * 3 + 2] = ao * b;
  }
  geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));
}

export class FighterModel {
  readonly root: THREE.Group;
  private readonly bones = new Map<Joint, THREE.Bone>();
  private readonly materials: THREE.Material[] = [];
  private readonly geometries: THREE.BufferGeometry[] = [];
  private readonly meshes: THREE.SkinnedMesh[] = [];

  constructor(palette: FighterPalette) {
    this.root = new THREE.Group();

    for (const joint of JOINT_ORDER) {
      const spec = SKELETON[joint];
      const bone = new THREE.Bone();
      bone.position.set(spec.offset[0], spec.offset[1], spec.offset[2]);
      const parent = spec.parent === null ? this.root : this.bones.get(spec.parent);
      if (!parent) throw new Error(`joint ${joint} has an unbuilt parent`);
      parent.add(bone);
      this.bones.set(joint, bone);
    }

    // Inverse bind matrices are taken from the bones as they stand, so the skeleton has to be
    // in its rest pose — and its world matrices up to date — at the moment it is constructed.
    this.root.updateMatrixWorld(true);
    const ordered = JOINT_ORDER.map((joint) => this.bones.get(joint)!);
    const skeleton = new THREE.Skeleton(ordered);

    const noise = surfaceNoise();
    const skin = skinMaterial(palette, noise);
    const trunks = new THREE.MeshStandardMaterial({
      vertexColors: true,
      color: palette.trunks,
      roughness: 0.9,
      metalness: 0,
      roughnessMap: noise,
    });
    const gloves = new THREE.MeshPhysicalMaterial({
      vertexColors: true,
      color: palette.gloves,
      roughness: 0.42,
      metalness: 0,
      clearcoat: 0.55,
      clearcoatRoughness: 0.35,
      roughnessMap: noise,
    });
    // Hair is dark, rough and reads almost entirely as silhouette at this distance, so it
    // wants no specular to speak of; the eyes want the opposite.
    const hair = new THREE.MeshStandardMaterial({
      vertexColors: true,
      color: palette.hair,
      roughness: 0.82,
      metalness: 0,
      roughnessMap: noise,
    });
    const eyes = new THREE.MeshStandardMaterial({ color: 0x140f0c, roughness: 0.28, metalness: 0 });
    this.materials.push(skin, trunks, gloves, hair, eyes);

    const parts: [ReturnType<typeof buildSkin>, THREE.Material, boolean][] = [
      [buildSkin(), skin, true],
      [buildShorts(), trunks, true],
      [buildGloves(), gloves, true],
      [buildHair(palette.hairStyle), hair, false],
      [buildFace(), eyes, false],
    ];
    if (palette.beard) parts.push([buildBeard(), hair, false]);

    for (const [data, material, casts] of parts) {
      const geometry = toGeometry(data);
      // Skin gets the tone gradient as well; cloth and hair only want the occlusion.
      if (material !== eyes) shade(geometry, material === skin);
      this.geometries.push(geometry);
      const mesh = new THREE.SkinnedMesh(geometry, material);
      mesh.castShadow = casts;
      mesh.receiveShadow = true;
      // Skinned bounds go stale as the pose changes; culling on them drops limbs mid-punch.
      mesh.frustumCulled = false;
      this.root.add(mesh);
      mesh.bind(skeleton);
      this.meshes.push(mesh);
    }
  }

  /** Pushes a resolved pose into the skeleton. Called once per fighter per frame. */
  applyPose(pose: ResolvedPose): void {
    for (const [joint, bone] of this.bones) {
      const rotation = pose.joints[joint];
      bone.rotation.set(rotation[0], rotation[1], rotation[2]);
    }
    const hips = this.bones.get('hips');
    if (hips) {
      const base = SKELETON.hips.offset;
      hips.position.set(base[0] + pose.offset[0], base[1] + pose.offset[1], base[2] + pose.offset[2]);
    }
  }

  setPlacement(position: Vec3, yaw: number): void {
    this.root.position.set(position[0], position[1], position[2]);
    this.root.rotation.y = yaw;
  }

  /** World position of the head, which the camera frames on. */
  headPosition(target: THREE.Vector3): THREE.Vector3 {
    const head = this.bones.get('head');
    if (!head) return target.set(0, 1.6, 0);
    return head.getWorldPosition(target);
  }

  dispose(): void {
    for (const geometry of this.geometries) geometry.dispose();
    for (const material of this.materials) material.dispose();
    for (const mesh of this.meshes) mesh.skeleton.dispose();
    this.geometries.length = 0;
    this.materials.length = 0;
    this.meshes.length = 0;
    this.bones.clear();
  }
}

export type { FighterPalette } from './palette.ts';
export { PALETTE_A, PALETTE_B } from './palette.ts';
